[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:starlette.*:
    ignore::DeprecationWarning:anyio.*:
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*
    ignore:.*The anyio.abc.BlockingPortal alias is deprecated.*
    ignore::Warning:fastapi.testclient
